// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: protobuf/auctions_run_service.proto

package auctions_run_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuctionsRunServiceClient is the client API for AuctionsRunService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionsRunServiceClient interface {
	SuggestPrice(ctx context.Context, in *SuggestPriceRequest, opts ...grpc.CallOption) (*SuggestPriceResponse, error)
	GetCurrentPrice(ctx context.Context, in *GetCurrentPriceRequest, opts ...grpc.CallOption) (AuctionsRunService_GetCurrentPriceClient, error)
}

type auctionsRunServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionsRunServiceClient(cc grpc.ClientConnInterface) AuctionsRunServiceClient {
	return &auctionsRunServiceClient{cc}
}

func (c *auctionsRunServiceClient) SuggestPrice(ctx context.Context, in *SuggestPriceRequest, opts ...grpc.CallOption) (*SuggestPriceResponse, error) {
	out := new(SuggestPriceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.AuctionsRunService/SuggestPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionsRunServiceClient) GetCurrentPrice(ctx context.Context, in *GetCurrentPriceRequest, opts ...grpc.CallOption) (AuctionsRunService_GetCurrentPriceClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuctionsRunService_ServiceDesc.Streams[0], "/protobuf.AuctionsRunService/GetCurrentPrice", opts...)
	if err != nil {
		return nil, err
	}
	x := &auctionsRunServiceGetCurrentPriceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuctionsRunService_GetCurrentPriceClient interface {
	Recv() (*GetCurrentPriceResponse, error)
	grpc.ClientStream
}

type auctionsRunServiceGetCurrentPriceClient struct {
	grpc.ClientStream
}

func (x *auctionsRunServiceGetCurrentPriceClient) Recv() (*GetCurrentPriceResponse, error) {
	m := new(GetCurrentPriceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuctionsRunServiceServer is the server API for AuctionsRunService service.
// All implementations must embed UnimplementedAuctionsRunServiceServer
// for forward compatibility
type AuctionsRunServiceServer interface {
	SuggestPrice(context.Context, *SuggestPriceRequest) (*SuggestPriceResponse, error)
	GetCurrentPrice(*GetCurrentPriceRequest, AuctionsRunService_GetCurrentPriceServer) error
}

// UnimplementedAuctionsRunServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionsRunServiceServer struct {
}

func (UnimplementedAuctionsRunServiceServer) SuggestPrice(context.Context, *SuggestPriceRequest) (*SuggestPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestPrice not implemented")
}
func (UnimplementedAuctionsRunServiceServer) GetCurrentPrice(*GetCurrentPriceRequest, AuctionsRunService_GetCurrentPriceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCurrentPrice not implemented")
}
func (UnimplementedAuctionsRunServiceServer) mustEmbedUnimplementedAuctionsRunServiceServer() {}

// UnsafeAuctionsRunServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionsRunServiceServer will
// result in compilation errors.
type UnsafeAuctionsRunServiceServer interface {
	mustEmbedUnimplementedAuctionsRunServiceServer()
}

func RegisterAuctionsRunServiceServer(s grpc.ServiceRegistrar, srv AuctionsRunServiceServer) {
	s.RegisterService(&AuctionsRunService_ServiceDesc, srv)
}

func _AuctionsRunService_SuggestPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionsRunServiceServer).SuggestPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.AuctionsRunService/SuggestPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionsRunServiceServer).SuggestPrice(ctx, req.(*SuggestPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionsRunService_GetCurrentPrice_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCurrentPriceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuctionsRunServiceServer).GetCurrentPrice(m, &auctionsRunServiceGetCurrentPriceServer{stream})
}

type AuctionsRunService_GetCurrentPriceServer interface {
	Send(*GetCurrentPriceResponse) error
	grpc.ServerStream
}

type auctionsRunServiceGetCurrentPriceServer struct {
	grpc.ServerStream
}

func (x *auctionsRunServiceGetCurrentPriceServer) Send(m *GetCurrentPriceResponse) error {
	return x.ServerStream.SendMsg(m)
}

// AuctionsRunService_ServiceDesc is the grpc.ServiceDesc for AuctionsRunService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionsRunService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.AuctionsRunService",
	HandlerType: (*AuctionsRunServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuggestPrice",
			Handler:    _AuctionsRunService_SuggestPrice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCurrentPrice",
			Handler:       _AuctionsRunService_GetCurrentPrice_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/auctions_run_service.proto",
}
