// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auctions_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Auction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrganizerID          int64    `protobuf:"varint,4,opt,name=organizerID,proto3" json:"organizerID,omitempty"`
	MaxParticipants      int32    `protobuf:"varint,5,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	ParticipantsNumber   int32    `protobuf:"varint,6,opt,name=participants_number,json=participantsNumber,proto3" json:"participants_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auction) Reset()         { *m = Auction{} }
func (m *Auction) String() string { return proto.CompactTextString(m) }
func (*Auction) ProtoMessage()    {}
func (*Auction) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{0}
}

func (m *Auction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auction.Unmarshal(m, b)
}
func (m *Auction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auction.Marshal(b, m, deterministic)
}
func (m *Auction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auction.Merge(m, src)
}
func (m *Auction) XXX_Size() int {
	return xxx_messageInfo_Auction.Size(m)
}
func (m *Auction) XXX_DiscardUnknown() {
	xxx_messageInfo_Auction.DiscardUnknown(m)
}

var xxx_messageInfo_Auction proto.InternalMessageInfo

func (m *Auction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Auction) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Auction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Auction) GetOrganizerID() int64 {
	if m != nil {
		return m.OrganizerID
	}
	return 0
}

func (m *Auction) GetMaxParticipants() int32 {
	if m != nil {
		return m.MaxParticipants
	}
	return 0
}

func (m *Auction) GetParticipantsNumber() int32 {
	if m != nil {
		return m.ParticipantsNumber
	}
	return 0
}

type Product struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuctionId            string            `protobuf:"bytes,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Title                string            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartPrice           int64             `protobuf:"varint,5,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	Category             string            `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Params               map[string]string `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetStartPrice() int64 {
	if m != nil {
		return m.StartPrice
	}
	return 0
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateAuctionRequest struct {
	Auction              *Auction `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuctionRequest) Reset()         { *m = CreateAuctionRequest{} }
func (m *CreateAuctionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAuctionRequest) ProtoMessage()    {}
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{3}
}

func (m *CreateAuctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuctionRequest.Unmarshal(m, b)
}
func (m *CreateAuctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuctionRequest.Marshal(b, m, deterministic)
}
func (m *CreateAuctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuctionRequest.Merge(m, src)
}
func (m *CreateAuctionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAuctionRequest.Size(m)
}
func (m *CreateAuctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuctionRequest proto.InternalMessageInfo

func (m *CreateAuctionRequest) GetAuction() *Auction {
	if m != nil {
		return m.Auction
	}
	return nil
}

type UpdateAuctionRequest struct {
	Auction              *Auction `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAuctionRequest) Reset()         { *m = UpdateAuctionRequest{} }
func (m *UpdateAuctionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAuctionRequest) ProtoMessage()    {}
func (*UpdateAuctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{4}
}

func (m *UpdateAuctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuctionRequest.Unmarshal(m, b)
}
func (m *UpdateAuctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuctionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAuctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuctionRequest.Merge(m, src)
}
func (m *UpdateAuctionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAuctionRequest.Size(m)
}
func (m *UpdateAuctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuctionRequest proto.InternalMessageInfo

func (m *UpdateAuctionRequest) GetAuction() *Auction {
	if m != nil {
		return m.Auction
	}
	return nil
}

type DeleteAuctionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuctionRequest) Reset()         { *m = DeleteAuctionRequest{} }
func (m *DeleteAuctionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAuctionRequest) ProtoMessage()    {}
func (*DeleteAuctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{5}
}

func (m *DeleteAuctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuctionRequest.Unmarshal(m, b)
}
func (m *DeleteAuctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuctionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAuctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuctionRequest.Merge(m, src)
}
func (m *DeleteAuctionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAuctionRequest.Size(m)
}
func (m *DeleteAuctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuctionRequest proto.InternalMessageInfo

func (m *DeleteAuctionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddParticipantRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ParticipantId        string   `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddParticipantRequest) Reset()         { *m = AddParticipantRequest{} }
func (m *AddParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*AddParticipantRequest) ProtoMessage()    {}
func (*AddParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{6}
}

func (m *AddParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddParticipantRequest.Unmarshal(m, b)
}
func (m *AddParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddParticipantRequest.Marshal(b, m, deterministic)
}
func (m *AddParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddParticipantRequest.Merge(m, src)
}
func (m *AddParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_AddParticipantRequest.Size(m)
}
func (m *AddParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddParticipantRequest proto.InternalMessageInfo

func (m *AddParticipantRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *AddParticipantRequest) GetParticipantId() string {
	if m != nil {
		return m.ParticipantId
	}
	return ""
}

type DeleteParticipantRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ParticipantId        string   `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteParticipantRequest) Reset()         { *m = DeleteParticipantRequest{} }
func (m *DeleteParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteParticipantRequest) ProtoMessage()    {}
func (*DeleteParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{7}
}

func (m *DeleteParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParticipantRequest.Unmarshal(m, b)
}
func (m *DeleteParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParticipantRequest.Marshal(b, m, deterministic)
}
func (m *DeleteParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParticipantRequest.Merge(m, src)
}
func (m *DeleteParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteParticipantRequest.Size(m)
}
func (m *DeleteParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParticipantRequest proto.InternalMessageInfo

func (m *DeleteParticipantRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *DeleteParticipantRequest) GetParticipantId() string {
	if m != nil {
		return m.ParticipantId
	}
	return ""
}

type AddProductRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductRequest) Reset()         { *m = AddProductRequest{} }
func (m *AddProductRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductRequest) ProtoMessage()    {}
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{8}
}

func (m *AddProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductRequest.Unmarshal(m, b)
}
func (m *AddProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductRequest.Marshal(b, m, deterministic)
}
func (m *AddProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductRequest.Merge(m, src)
}
func (m *AddProductRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductRequest.Size(m)
}
func (m *AddProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductRequest proto.InternalMessageInfo

func (m *AddProductRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *AddProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{9}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *UpdateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DeletePoductRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePoductRequest) Reset()         { *m = DeletePoductRequest{} }
func (m *DeletePoductRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePoductRequest) ProtoMessage()    {}
func (*DeletePoductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a800747a237704, []int{10}
}

func (m *DeletePoductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePoductRequest.Unmarshal(m, b)
}
func (m *DeletePoductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePoductRequest.Marshal(b, m, deterministic)
}
func (m *DeletePoductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePoductRequest.Merge(m, src)
}
func (m *DeletePoductRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePoductRequest.Size(m)
}
func (m *DeletePoductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePoductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePoductRequest proto.InternalMessageInfo

func (m *DeletePoductRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

func (m *DeletePoductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func init() {
	proto.RegisterType((*Auction)(nil), "protobuf.Auction")
	proto.RegisterType((*Product)(nil), "protobuf.Product")
	proto.RegisterMapType((map[string]string)(nil), "protobuf.Product.ParamsEntry")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
	proto.RegisterType((*CreateAuctionRequest)(nil), "protobuf.CreateAuctionRequest")
	proto.RegisterType((*UpdateAuctionRequest)(nil), "protobuf.UpdateAuctionRequest")
	proto.RegisterType((*DeleteAuctionRequest)(nil), "protobuf.DeleteAuctionRequest")
	proto.RegisterType((*AddParticipantRequest)(nil), "protobuf.AddParticipantRequest")
	proto.RegisterType((*DeleteParticipantRequest)(nil), "protobuf.DeleteParticipantRequest")
	proto.RegisterType((*AddProductRequest)(nil), "protobuf.AddProductRequest")
	proto.RegisterType((*UpdateProductRequest)(nil), "protobuf.UpdateProductRequest")
	proto.RegisterType((*DeletePoductRequest)(nil), "protobuf.DeletePoductRequest")
}

func init() {
	proto.RegisterFile("auctions_service.proto", fileDescriptor_58a800747a237704)
}

var fileDescriptor_58a800747a237704 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x6d, 0x6b, 0x13, 0x4d,
	0x14, 0x7d, 0x36, 0xdb, 0x24, 0xcd, 0x0d, 0x7d, 0xc9, 0x34, 0x4f, 0x59, 0x22, 0xb1, 0x61, 0x41,
	0x89, 0x14, 0x52, 0x88, 0x08, 0xea, 0x17, 0xa9, 0x49, 0x91, 0x7c, 0x50, 0xc2, 0x16, 0x11, 0x04,
	0x59, 0x27, 0x3b, 0x63, 0x59, 0x4c, 0x76, 0xd7, 0x99, 0xd9, 0xd2, 0xf8, 0x67, 0xfc, 0x43, 0x82,
	0x7f, 0x49, 0x76, 0x76, 0xa6, 0x99, 0xcd, 0x8b, 0x8d, 0x48, 0x3f, 0x25, 0xf7, 0xdc, 0x3b, 0x67,
	0xee, 0xb9, 0xf7, 0xcc, 0xc2, 0x31, 0x4e, 0x03, 0x11, 0xc6, 0x11, 0xf7, 0x39, 0x65, 0xd7, 0x61,
	0x40, 0x7b, 0x09, 0x8b, 0x45, 0x8c, 0x76, 0xe5, 0xcf, 0x24, 0xfd, 0xe2, 0xfe, 0xb2, 0xa0, 0x7a,
	0x9e, 0x17, 0xa1, 0x7d, 0x28, 0x85, 0xc4, 0xb1, 0x3a, 0x56, 0xb7, 0xe6, 0x95, 0x42, 0x82, 0x9a,
	0x50, 0x16, 0xa1, 0x98, 0x52, 0xa7, 0x24, 0xa1, 0x3c, 0x40, 0x1d, 0xa8, 0x13, 0xca, 0x03, 0x16,
	0x26, 0xd9, 0x21, 0xc7, 0x96, 0x39, 0x13, 0xca, 0x2a, 0x62, 0x76, 0x85, 0xa3, 0xf0, 0x3b, 0x65,
	0xa3, 0xa1, 0xb3, 0xd3, 0xb1, 0xba, 0xb6, 0x67, 0x42, 0xe8, 0x09, 0x1c, 0xce, 0xf0, 0x8d, 0x9f,
	0x60, 0x26, 0xc2, 0x20, 0x4c, 0x70, 0x24, 0xb8, 0x53, 0xee, 0x58, 0xdd, 0xb2, 0x77, 0x30, 0xc3,
	0x37, 0x63, 0x03, 0x46, 0x67, 0x70, 0x64, 0x96, 0xf9, 0x51, 0x3a, 0x9b, 0x50, 0xe6, 0x54, 0x64,
	0x35, 0x32, 0x53, 0xef, 0x64, 0xc6, 0xfd, 0x51, 0x82, 0xea, 0x98, 0xc5, 0x24, 0x0d, 0x84, 0xa1,
	0xc8, 0x96, 0x8a, 0xda, 0x00, 0x6a, 0x22, 0x7e, 0x48, 0x94, 0xac, 0x9a, 0x42, 0x46, 0x86, 0x60,
	0xfb, 0x0f, 0x82, 0x77, 0x56, 0x05, 0x9f, 0x40, 0x9d, 0x0b, 0xcc, 0x84, 0x9f, 0xb0, 0x30, 0xa0,
	0x52, 0x89, 0xed, 0x81, 0x84, 0xc6, 0x19, 0x82, 0x5a, 0xb0, 0x1b, 0x60, 0x41, 0xaf, 0x62, 0x36,
	0x97, 0x9d, 0xd7, 0xbc, 0xdb, 0x18, 0x3d, 0x83, 0x4a, 0x82, 0x19, 0x9e, 0x71, 0xa7, 0xda, 0xb1,
	0xbb, 0xf5, 0x7e, 0xbb, 0xa7, 0x97, 0xd3, 0x53, 0x32, 0x7a, 0x63, 0x99, 0xbf, 0x88, 0x04, 0x9b,
	0x7b, 0xaa, 0xb8, 0xf5, 0x02, 0xea, 0x06, 0x8c, 0x0e, 0xc1, 0xfe, 0x4a, 0xe7, 0x6a, 0x79, 0xd9,
	0xdf, 0x4c, 0xcc, 0x35, 0x9e, 0xa6, 0xb7, 0xdb, 0x93, 0xc1, 0xcb, 0xd2, 0x73, 0xcb, 0xfd, 0x00,
	0xbb, 0x1e, 0xe5, 0x49, 0x1c, 0x71, 0x8a, 0x8e, 0xa1, 0xc2, 0x05, 0x16, 0x29, 0x57, 0x47, 0x55,
	0x94, 0x4d, 0x8a, 0x32, 0x16, 0x33, 0x3f, 0x88, 0x49, 0x4e, 0x51, 0xf6, 0x6a, 0x12, 0x19, 0xc4,
	0x84, 0x66, 0xe4, 0x32, 0xd0, 0x93, 0x92, 0x81, 0x3b, 0x80, 0xe6, 0x80, 0x51, 0x2c, 0xa8, 0x72,
	0x94, 0x47, 0xbf, 0xa5, 0x94, 0x0b, 0x74, 0x0a, 0x55, 0x35, 0x64, 0x79, 0x4b, 0xbd, 0xdf, 0x58,
	0x68, 0xd4, 0xa5, 0xba, 0x22, 0x23, 0x79, 0x9f, 0x90, 0x7f, 0x24, 0x79, 0x0c, 0xcd, 0x21, 0x9d,
	0xd2, 0x15, 0x92, 0x25, 0x8b, 0xbb, 0x9f, 0xe0, 0xff, 0x73, 0x42, 0x0c, 0xc3, 0xe9, 0xc2, 0xa2,
	0x53, 0xac, 0x65, 0xa7, 0x3c, 0x82, 0x7d, 0xc3, 0x7a, 0x0b, 0x33, 0xed, 0x19, 0xe8, 0x88, 0xb8,
	0x9f, 0xc1, 0xc9, 0xdb, 0xb8, 0xb7, 0x1b, 0x7c, 0x68, 0x64, 0x02, 0x72, 0xa3, 0x6c, 0x49, 0x7d,
	0x0a, 0xd5, 0x24, 0x3f, 0x20, 0x39, 0x0b, 0x93, 0xd4, 0x4c, 0xba, 0xc2, 0x9d, 0xe8, 0x75, 0xdc,
	0xe3, 0x1d, 0x97, 0x70, 0xa4, 0xc6, 0xf4, 0x37, 0x57, 0xb4, 0x01, 0x14, 0x81, 0xf1, 0x98, 0x15,
	0x32, 0x22, 0xfd, 0x9f, 0x3b, 0x70, 0xa0, 0xb6, 0xcf, 0x2f, 0xf3, 0xaf, 0x1f, 0xba, 0x80, 0xbd,
	0x82, 0x41, 0xd1, 0xc3, 0x45, 0x57, 0xeb, 0x9c, 0xdb, 0x42, 0x8b, 0xbc, 0x7e, 0x32, 0xee, 0x7f,
	0x19, 0x4d, 0xc1, 0xa2, 0x26, 0xcd, 0x3a, 0xef, 0x6e, 0xa6, 0x29, 0x98, 0xd4, 0xa4, 0x59, 0xe7,
	0xde, 0x0d, 0x34, 0x6f, 0x60, 0xbf, 0xe8, 0x61, 0x74, 0x62, 0xbc, 0x8c, 0x75, 0xee, 0xde, 0x40,
	0xf4, 0x16, 0x1a, 0x2b, 0x6e, 0x45, 0xee, 0x72, 0x4f, 0x5b, 0xd3, 0xbd, 0x02, 0x58, 0x58, 0x13,
	0x3d, 0x28, 0xf6, 0x54, 0x30, 0xd3, 0x5d, 0x63, 0xd6, 0x1c, 0x2b, 0x63, 0xde, 0x8a, 0x66, 0xa8,
	0xc7, 0xac, 0x69, 0xda, 0x2b, 0x92, 0xee, 0x66, 0x79, 0x5d, 0xfe, 0x68, 0x9f, 0x25, 0x93, 0x49,
	0x45, 0xe6, 0x9e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x70, 0x96, 0xa0, 0x5a, 0x07, 0x00,
	0x00,
}
